import { defineField, defineType } from "sanity";

export default defineType({
  name: "service",
  title: "Service",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "deliverables", title: "Deliverables" },
    { name: "work", title: "Work + metrics" },
    { name: "process", title: "Process" },
    { name: "faqs", title: "FAQs" },
    { name: "publish", title: "Publishing" },
  ],
  fields: [
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 64 },
      description:
        "Must be one of: personal-brand, post-production, podcast-distribution, launch-videos, clipping.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "num",
      title: "Number",
      type: "string",
      group: "content",
      description: "e.g. \"01\"–\"05\"",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline / hero dek",
      type: "text",
      rows: 4,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "pills",
      title: "Tag pills",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "description",
      title: "Overview row description",
      type: "text",
      rows: 2,
      group: "content",
      description:
        "Short description shown on the /services overview row.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "deliverablesMeta",
      title: "Deliverables meta",
      type: "string",
      group: "deliverables",
    }),
    defineField({
      name: "deliverables",
      title: "Deliverables (exactly 3)",
      type: "array",
      group: "deliverables",
      of: [{ type: "deliverable" }],
      validation: (r) => r.min(3).max(3),
    }),
    defineField({
      name: "workHeading",
      title: "Work section heading",
      type: "string",
      group: "work",
    }),
    defineField({
      name: "workMeta",
      title: "Work section meta",
      type: "string",
      group: "work",
    }),
    defineField({
      name: "workSamples",
      title: "Work samples",
      type: "array",
      group: "work",
      of: [{ type: "workSample" }],
      validation: (r) => r.max(8),
    }),
    defineField({
      name: "metricsMeta",
      title: "Metrics meta",
      type: "string",
      group: "work",
    }),
    defineField({
      name: "metrics",
      title: "Metrics (exactly 3)",
      type: "array",
      group: "work",
      of: [{ type: "serviceMetric" }],
      validation: (r) => r.min(3).max(3),
    }),
    defineField({
      name: "processMeta",
      title: "Process meta",
      type: "string",
      group: "process",
    }),
    defineField({
      name: "process",
      title: "Process steps",
      type: "array",
      group: "process",
      of: [{ type: "processStep" }],
      validation: (r) => r.min(2).max(6),
    }),
    defineField({
      name: "ctaHeading",
      title: "Bottom CTA heading",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      group: "faqs",
      of: [{ type: "serviceFaq" }],
    }),
    defineField({
      name: "published",
      title: "Published?",
      type: "boolean",
      group: "publish",
      initialValue: true,
    }),
  ],
  orderings: [
    {
      title: "Service number",
      name: "numAsc",
      by: [{ field: "num", direction: "asc" }],
    },
  ],
  preview: {
    select: { num: "num", title: "title", published: "published" },
    prepare: ({ num, title, published }) => ({
      title: `${num} · ${title}`,
      subtitle: published === false ? "HIDDEN" : undefined,
    }),
  },
});
